when:
  - event: push
    branch: master
    path:
      include: [ '.woodpecker/build-docs.yaml', 'docs/*', 'mkdocs.yml' ]

steps:
  - name: build
    image: woodpeckerci/plugin-mkdocs:minimal
  - name: deploy
    image: codeberg.org/xfix/plugin-codeberg-pages-deploy:1
    settings:
      folder: site
      ssh_key:
        from_secret: codeberg-ssh-key

depends_on:
  - checkout-code